### ISSUE TITLE
Selected Sphere Issue

### ISSUE THREAD

**Issue by rober706** [bdrown/chm696-docking#2]
Hi, I am at the step for generating my ligand binding site spheres and it is not showing selected spheres for ligand binding; it instead shows basically all spheres except for 2 (seen by overlaying my selected spheres will all spheres). I have checked my .mol2 file for ligand only and it is correct. Everything up to this point has been checked and looks correct. Any help would be greatly appreciated!

**Comment by bdrown** [comment]
Which starting structure are you using (PDB entry)?

**Comment by rober706** [comment]
I am using the 2W9G protein

**Comment by bdrown** [comment]
DHFR has two ligands bound (trimethoprim and NADPH). Are you sure you selected trimethoprim?

**Comment by rober706** [comment]
I see, both are currently selected. I will dry deleting the NADPH

**Comment by bdrown** [comment]
Sounds good. I was able to do the original ligand redocking with NADPH as part of the receptor grid. There's more than one way to handle cofactors but removing them is certainly the simplest.

**Comment by rober706** [comment]
It worked! Thank you

**Comment by bdrown** [comment]
Glad to hear it!
