### ISSUE TITLE
Issues: Modeller Step

### ISSUE THREAD

**Issue by judequarshie** [bdrown/chm696-docking#3]
When I try fixing the missing residues of 2ITO as taught in the tutorials, the taskbar says the task is completed (in about 2 seconds) but I never get the pop-up with the different new fixed structures.

**Comment by bdrown** [comment]
That means Modeller is failing. I'm recommending that students use the web service instead of the local installation. Use the license key that is posted as part of a Brightspace announcement.

**Comment by judequarshie** [comment]
It worked! Thank you very much.
